<?php
return [
    [
        'id' => 1,
        'email' => "mark.henderson@8trk.com",
        'firstname' => "Mark",
        'lastname' => "Henderson",
        'report' => "I got a new job. More money + more time at home (it is remote: the future) = a happier me.",
        'canShare' => "Yes",
        'hasImage' => "No",
    ],
    [
        'id' => 2,
        'email' => "ms.chinaemere@gmail.com",
        'firstname' => "Chinaemere",
        'lastname' => "Ike",
        'report' => "My A (99%) on my Calculus exam! I've struggled so much with math but ya girl is out here prospering now. I am so proud of myself! :)",
        'canShare' => "Yes",
        'hasImage' => "No",
    ],
    [
        'id' => 3,
        'email' => "mxmariweaver@gmx.co.uk",
        'firstname' => "Tomie",
        'lastname' => "Weaver",
        'report' => "I completed a due diligence report about other databases my org considered before making a decision on how to proceed.",
        'canShare' => "Yes",
        'hasImage' => "Yes",
        'moreHype' => "writing essays about media culture and making progress in my online courses",
    ],
    [
        'id' => 4,
        'email' => "miaimarshall@gmail.com",
        'firstname' => "Mia",
        'lastname' => "Marshall",
        'report' => "I received confirmation that I will be a speaker for the first time ever at a tech conference!",
        'canShare' => "Yes",
        'hasImage' => "No",
    ],
    [
        'id' => 5,
        'email' => "askambernechole@gmail.com",
        'firstname' => "AmberNechole",
        'lastname' => "Hart",
        'report' => "I planned and executed the FIRST Black History Month celebration at my job. ",
        'canShare' => "Yes",
        'hasImage' => "No",
        'moreHype' => "I drafted my CFP for the REFACTR conference!",
    ],
    [
        'id' => 6,
        'email' => "p.mbanugo@yahoo.com",
        'firstname' => "Peter",
        'lastname' => "Mbanugo",
        'report' => "More signups for my product Hamoni Inc. ",
        'canShare' => "Yes",
        'happier' => "No",
    ],
    [
        'id' => 7,
        'email' => "lrnzdavis@gmail.com",
        'firstname' => "Lorenzo Fernando",
        'lastname' => "Davis",
        'report' => "Promotion to Director of Infrastructure and Security",
        'canShare' => "Yes",
        'hasImage' => "No",
    ],
];
